repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.8.0
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.0
  args: [--config=".flake8"]
  hooks:
  - id: flake8
- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: poetry run mypy --namespace-packages --explicit-package-bases msu_atpase_storage
    pass_filenames: false
    language: system
    types: [python]
